config/routes.rb
Rails.application.routes.draw do
  get 'anchor/index'
  get 'anchor/discussion'

  get 'anchor/mark_as_read'
  post 'anchor/mark_as_read'
  patch 'anchor/mark_as_read'
  put 'anchor/mark_as_read'
  delete 'anchor/mark_as_read'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "anchor#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/anchor_controller.rb
class AnchorController < ApplicationController
  def index
  end

  def mark_as_read
    redirect_to anchor_discussion_path(anchor: "comment_100"), status: :see_other
  end

  def discussion
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Custom redirect_to logic to transparently support redirects with anchors so Turbo
  # works as expected. The general approach is to leverage a query parameter to proxy the anchor value
  # (as the anchor/fragment is lost when using Turbo and the browser fetch() follow code).
  #
  # This code looks for an anchor (#comment_100), if it finds one it will add a new query parameter of
  # "_anchor=comment_100" and then remove the anchor value.
  #
  # The resulting URL is then passed through to the redirect_to call
  def redirect_to(options = {}, response_options = {})
    # https://edgeapi.rubyonrails.org/classes/ActionController/Redirecting.html
    # We want to be conservative on when this is applied. Only a string path is allowed,
    # a limited set of methods and only the 303/see_other status code
    if options.is_a?(String) &&
        %w[GET PATCH PUT POST DELETE].include?(request.request_method) &&
        [:see_other, 303].include?(response_options[:status])

      # parse the uri, where options is the string of the url
      uri = URI.parse(options)

      # check if there is a fragment present
      if uri.fragment.present?
        params = uri.query.present? ? CGI.parse(uri.query) : {}

        # set a new query parameter of _anchor, with the anchor value
        params["_anchor"] = uri.fragment

        # re-encode the query parameters
        uri.query = URI.encode_www_form(params)

        # clear the fragment
        uri.fragment = ""
      end
      options = uri.to_s
    end

    # call the regular redirect_to method
    super
  end
end

app/helpers/anchor_helper.rb
module AnchorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/anchor/discussion.html.erb
<h1>Turbo Anchors</h1>

<%= link_to "Back to Index", anchor_index_path %>

<p>
  Here are some sample comments.
</p>

<ul>
  <% (1..99).each do |comment| %>
 <li>This is a sample comment <%= comment %></li>
  <% end %>
</ul>


<turbo-frame id="comment_100" style="background-color: green;">
 <h1>COMMENT 100</h1>
 <p>
    This is the comment that we were notified about and want to scroll to automatically 
    via the <code>comment_100</code> page anchor.
 </p>
</turbo-frame>

<ul>
  <% (101..200).each do |comment| %>
 <li>This is a sample comment <%= comment %></li>
  <% end %>
</ul>

<turbo-frame id="bad_comment">
 <h1>BAD COMMENT</h1>
 <p>
    How did we get here? The <code>link_to</code> anchor is taking over the redirect to anchor (i.e. the browser Location
    is <code>comment_100</code> but the link_to was <code>bad_comment</code>).
 </p>
</turbo-frame>

app/views/anchor/index.html.erb
<h1>Turbo Anchors</h1>

<p>
 The purpose of this site is to demonstrate how turbo behaves with anchors. A common pattern that we use is in-app
 notifications (with noticed of cours!), where we have an endpoint to mark a notification as read and then redirect 
 the user to the relevant page. The general flow looks like:
</p>

<ol>
  <li>Link clicked to follow notification (i.e. user mentioned in a discussion comment)</li>
  <li>Notification marked as read</li>
  <li>User redirected to the related notification endpoint (i.e. a specific comment added to a discussion thread)</li>
</ol>

<p>
 The controller endpoint always returns with a redirect to this page, with an anchor of <code>comment_100</code>. 
</p>

<p>
 The expected result for clicking on any "test" link is that the page should scroll to the green, <code>comment_100</code>.
</p>

<table>
  <tr>
    <th>Method</th>
    <th>Turbo</th>
    <th>URL</th>
    <th>Target</th>
    <th>Test</th>
    <th>Status</th>
    <th>Comments</th>
  </tr>
  <tr>
    <td>patch</td>
    <td>yes</td>
    <td><%= anchor_mark_as_read_path %></td>
    <td>comment_100</td>
    <td><%= link_to "test", anchor_mark_as_read_path, data: { "turbo-method": :patch } %></td>
    <td style="color: red;">fail</td>
    <td>Does nothing.</td>
  </tr>
  <tr>
    <td>get</td>
    <td>yes</td>
    <td><%= anchor_mark_as_read_path %></td>
    <td>comment_100</td>
    <td><%= link_to "test", anchor_mark_as_read_path %></td>
    <td style="color: red;">fail</td>
    <td>Does nothing.</td>
  </tr>
  <tr>
    <td>get</td>
    <td>no</td>
    <td><%= anchor_mark_as_read_path %></td>
    <td>comment_100</td>
    <td><%= link_to "test", anchor_mark_as_read_path, data: { turbo: false } %></td>
    <td style="color: green;">pass</td>
    <td>No turbo, works as expected.</td>
  </tr>
  <tr>
    <td>patch</td>
    <td>yes</td>
    <td><%= anchor_mark_as_read_path(anchor: "comment_100") %></td>
    <td>comment_100</td>
    <td><%= link_to "test", anchor_mark_as_read_path(anchor: "comment_100"), data: { "turbo-method": :patch } %></td>
    <td style="color: red;">fail</td>
    <td>Specify the anchor in the link.</td>
  </tr>
  <tr>
    <td>get</td>
    <td>yes</td>
    <td><%= anchor_mark_as_read_path(anchor: "comment_100") %></td>
    <td>comment_100</td>
    <td><%= link_to "test", anchor_mark_as_read_path(anchor: "comment_100") %></td>
    <td style="color: green;">pass</td>
    <td>Specify the anchor in the link and it works "by accident".</td>
  </tr>
  <tr>
    <td>get</td>
    <td>yes</td>
    <td><%= anchor_mark_as_read_path(anchor: "bad_comment") %></td>
    <td>bad_comment</td>
    <td><%= link_to "test", anchor_mark_as_read_path(anchor: "bad_comment") %></td>
    <td style="color: red;">fail</td>
    <td>Also works in a completely unexpected way. The link_to anchor dominates the Location url.</td>
  </tr>
</table>


<p>
  General helpers to see what is going on with Turbo
</p>

<p>
  <%= link_to 'get', anchor_mark_as_read_path %> | 
  <%= link_to 'post', anchor_mark_as_read_path, data: { "turbo-method": :post } %> | 
  <%= link_to 'patch', anchor_mark_as_read_path, data: { "turbo-method": :patch } %> | 
  <%= link_to 'put', anchor_mark_as_read_path, data: { "turbo-method": :put } %> | 
  <%= link_to 'delete', anchor_mark_as_read_path, data: { "turbo-method": :delete } %> 
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboAnchorIssue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>